#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_parens)]
#![allow(unused_imports, dead_code, unused_variables, unused_unsafe)]


mod _mod;
pub use self::_mod::*;
mod structs;
pub use self::structs::*;
mod enums;
pub use self::enums::*;
mod apis;
pub use self::apis::*;
mod constants;
pub use self::constants::*;

mod resource;
pub use self::resource::*;
mod image;
pub use self::image::*;
mod bitmap;
pub use self::bitmap::*;
mod gradient_stop_collection;
pub use self::gradient_stop_collection::*;
mod brush;
pub use self::brush::*;
mod bitmap_brush;
pub use self::bitmap_brush::*;
mod solid_color_brush;
pub use self::solid_color_brush::*;
mod linear_gradient_brush;
pub use self::linear_gradient_brush::*;
mod radial_gradient_brush;
pub use self::radial_gradient_brush::*;
mod stroke_style;
pub use self::stroke_style::*;
mod geometry;
pub use self::geometry::*;
mod rectangle_geometry;
pub use self::rectangle_geometry::*;
mod rounded_rectangle_geometry;
pub use self::rounded_rectangle_geometry::*;
mod ellipse_geometry;
pub use self::ellipse_geometry::*;
mod geometry_group;
pub use self::geometry_group::*;
mod transformed_geometry;
pub use self::transformed_geometry::*;
mod geometry_sink;
pub use self::geometry_sink::*;
mod tessellation_sink;
pub use self::tessellation_sink::*;
mod path_geometry;
pub use self::path_geometry::*;
mod mesh;
pub use self::mesh::*;
mod layer;
pub use self::layer::*;
mod drawing_state_block;
pub use self::drawing_state_block::*;
mod render_target;
pub use self::render_target::*;
mod bitmap_render_target;
pub use self::bitmap_render_target::*;
mod hwnd_render_target;
pub use self::hwnd_render_target::*;
mod gdi_interop_render_target;
pub use self::gdi_interop_render_target::*;
mod dc_render_target;
pub use self::dc_render_target::*;
mod factory;
pub use self::factory::*;
mod gdi_metafile_sink;
pub use self::gdi_metafile_sink::*;
mod gdi_metafile;
pub use self::gdi_metafile::*;
mod command_sink;
pub use self::command_sink::*;
mod command_list;
pub use self::command_list::*;
mod print_control;
pub use self::print_control::*;
mod image_brush;
pub use self::image_brush::*;
mod bitmap_brush1;
pub use self::bitmap_brush1::*;
mod stroke_style1;
pub use self::stroke_style1::*;
mod path_geometry1;
pub use self::path_geometry1::*;
mod properties;
pub use self::properties::*;
mod effect;
pub use self::effect::*;
mod bitmap1;
pub use self::bitmap1::*;
mod color_context;
pub use self::color_context::*;
mod gradient_stop_collection1;
pub use self::gradient_stop_collection1::*;
mod drawing_state_block1;
pub use self::drawing_state_block1::*;
mod device_context;
pub use self::device_context::*;
mod device;
pub use self::device::*;
mod factory1;
pub use self::factory1::*;
mod multithread;
pub use self::multithread::*;
mod vertex_buffer;
pub use self::vertex_buffer::*;
mod resource_texture;
pub use self::resource_texture::*;
mod render_info;
pub use self::render_info::*;
mod draw_info;
pub use self::draw_info::*;
mod compute_info;
pub use self::compute_info::*;
mod transform_node;
pub use self::transform_node::*;
mod transform_graph;
pub use self::transform_graph::*;
mod transform;
pub use self::transform::*;
mod draw_transform;
pub use self::draw_transform::*;
mod compute_transform;
pub use self::compute_transform::*;
mod analysis_transform;
pub use self::analysis_transform::*;
mod source_transform;
pub use self::source_transform::*;
mod concrete_transform;
pub use self::concrete_transform::*;
mod blend_transform;
pub use self::blend_transform::*;
mod border_transform;
pub use self::border_transform::*;
mod offset_transform;
pub use self::offset_transform::*;
mod bounds_adjustment_transform;
pub use self::bounds_adjustment_transform::*;
mod effect_impl;
pub use self::effect_impl::*;
mod effect_context;
pub use self::effect_context::*;
mod geometry_realization;
pub use self::geometry_realization::*;
mod device_context1;
pub use self::device_context1::*;
mod device1;
pub use self::device1::*;
mod factory2;
pub use self::factory2::*;
mod command_sink1;
pub use self::command_sink1::*;
mod svg_attribute;
pub use self::svg_attribute::*;
mod svg_paint;
pub use self::svg_paint::*;
mod svg_stroke_dash_array;
pub use self::svg_stroke_dash_array::*;
mod svg_point_collection;
pub use self::svg_point_collection::*;
mod svg_path_data;
pub use self::svg_path_data::*;
mod svg_element;
pub use self::svg_element::*;
mod svg_document;
pub use self::svg_document::*;
mod ink_style;
pub use self::ink_style::*;
mod ink;
pub use self::ink::*;
mod gradient_mesh;
pub use self::gradient_mesh::*;
mod image_source;
pub use self::image_source::*;
mod image_source_from_wic;
pub use self::image_source_from_wic::*;
mod transformed_image_source;
pub use self::transformed_image_source::*;
mod lookup_table3d;
pub use self::lookup_table3d::*;
mod device_context2;
pub use self::device_context2::*;
mod device2;
pub use self::device2::*;
mod factory3;
pub use self::factory3::*;
mod command_sink2;
pub use self::command_sink2::*;
mod gdi_metafile1;
pub use self::gdi_metafile1::*;
mod gdi_metafile_sink1;
pub use self::gdi_metafile_sink1::*;
mod sprite_batch;
pub use self::sprite_batch::*;
mod device_context3;
pub use self::device_context3::*;
mod device3;
pub use self::device3::*;
mod factory4;
pub use self::factory4::*;
mod command_sink3;
pub use self::command_sink3::*;
mod svg_glyph_style;
pub use self::svg_glyph_style::*;
mod device_context4;
pub use self::device_context4::*;
mod device4;
pub use self::device4::*;
mod factory5;
pub use self::factory5::*;
mod command_sink4;
pub use self::command_sink4::*;
mod color_context1;
pub use self::color_context1::*;
mod device_context5;
pub use self::device_context5::*;
mod device5;
pub use self::device5::*;
mod factory6;
pub use self::factory6::*;
mod command_sink5;
pub use self::command_sink5::*;
mod device_context6;
pub use self::device_context6::*;
mod device6;
pub use self::device6::*;
mod factory7;
pub use self::factory7::*;
mod effect_context1;
pub use self::effect_context1::*;
mod effect_context2;
pub use self::effect_context2::*;
pub mod common;
