[package]
name = "d3d12-api-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#include = ["runtimes/dxc_2021_12_08/bin/x64/dxcompiler.dll"]

[dependencies]
